### ISSUE TITLE
time delay between fetches...

### ISSUE THREAD

**Issue by TheOncomingStorm** [dpapathanasiou/recipebook#1]
I'm adding one myself right now but you might consider adding a time delay between fetches for crawler.py. AllRecipes gets really upset if you crawl their site too fast and will at first just give you a "Too Many Requests" response which you might want to start looking for, and then if you continue they'll block your IP for 48 hours. I'm betting many of the other sites will as well.

**Comment by dpapathanasiou** [comment]
Good idea.

I've added a random pause in https://github.com/dpapathanasiou/recipebook/commit/1f599083dd40bef1aeafd2cb384a5793ef3ece0a and explained its usage in https://github.com/dpapathanasiou/recipebook/commit/48b66f50ac1cf7b719b2a67bb834c4a0af111860.

Another way around blocks is to use a common user agent string, as explained in the [updated README](https://github.com/dpapathanasiou/recipebook/blob/master/README.md#avoiding-server-blocks).
